# Generated by Django 4.0.4 on 2022-09-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField()),
                ('stname', models.CharField(max_length=50)),
                ('stemail', models.EmailField(max_length=50)),
                ('stpass', models.CharField(max_length=50)),
            ],
        ),
    ]
